
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run:
          name: AWS CLI install
          command: |
            pip3 install awscli
      - run:
          name: Set AWS Credentials
          command: |
            aws configure --profile default set aws_access_key_id $AWS_ACCESS_KEY_ID_CIRCLECI
            aws configure --profile default set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_CIRCLECI
            aws configure --profile default set region us-east-1
            aws configure --profile default list
      - run:
          name: Set AWS Credentials
          command: |
            aws configure --profile user2 set aws_access_key_id $AWS_ACCESS_KEY_ID_YOUI
            aws configure --profile user2 set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_YOUI
            aws configure --profile user2 set region us-east-1
            aws configure --profile user2 list
      - requires: ['approve']
      - aws-s3/copy:
          arguments: '--profile user2'
          from: testuploads3_carolina.txt
          to: s3://circlecitestupload

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - approve:
           type: approval
