
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run:
          name: Setting env/qa branch environment variables.
          command: |
            mkdir ~/.aws echo -e
            "[CARO]\naws_access_key_id=$AWS_ACCESS_KEY_ID_CARO\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY_CARO\n" > ~/.aws/credentials
      - aws-s3/copy:
          argument: --profile CARO
          from: testuploads3_carolina.txt
          to: s3://circlecitestupload
