
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY_ID_CARO
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_CARO
          from: testuploads3_carolina.txt
          to: s3://circlecitestupload
