
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.1.0
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      # - run:
      #     name: Setting env/qa branch environment variables.
      #     command: |
      #       mkdir ~/.aws
      #       echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID_CIRCLECI\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY_CIRCLECI\n" >> ~/.aws/credentials
      #       echo -e "[default]\nregion=us-east-1\noutput=text\n" >> ~/.aws/config
      #       echo -e "[user]\naws_access_key_id=$AWS_ACCESS_KEY_ID_CARO\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY_CARO\n" >> ~/.aws/credentials
      #       echo -e "[user]\nregion=us-east-1\noutput=text\n" >> ~/.aws/config
      - aws-cli/setup
      - run:
          name: Set AWS Credentials
          command: |
            aws configure --profile user1 set aws_access_key_id $AWS_ACCESS_KEY_ID_CIRCLECI
            aws configure --profile user1 set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_CIRCLECI
            aws configure --profile user1 set region us-east-1
            aws configure --profile user1 list
      - run:
          name: Set AWS Credentials
          command: |
            aws configure --profile user2 set aws_access_key_id $AWS_ACCESS_KEY_ID_CARO
            aws configure --profile user2 set aws_secret_access_key $TEST_AWS_SECRET_ACCESS_CARO
            aws configure --profile user2 set region us-east-1
            aws configure --profile user2 list
      - aws-s3/copy:
          arguments: '--profile user'
          from: testuploads3_carolina.txt
          to: s3://circlecitestupload
